Make Erlang cookie parametric
cloudant-labs/clouseau pull request #67
Opened 2023-02-08 14:55 UTC by pgj

When linked to CouchDB nodes, the Erlang cookie might be different from the one that is originally assumed.  Make it user-configurable on launching the instance to facilitate smoother integration.  The default value is left `monster`, therefore this change is backwards compatible.

2023-02-08 15:06 UTC, rnewson commented
history: in couchdb we recently prohibited the value `monster` for security reasons (many users left this value in place and their installs were exploited as a consequence). We did not follow through with how the dev launch for clouseau works.

Like dev/run in couchdb I suggest we follow this strategy;

1) we default to not explicitly setting the cookie, and let clouseau read the ~/.erlang.cookie file instead (same as dev/run)
2) Optionally you can specify the cookie, in which case the user is responsible for setting the same value for couchdb as for clouseau.

Implied in this is that the word `monster` will no longer appear in pom.xml.

2023-02-08 15:57 UTC, pgj commented
How can `clouseau` read the `~/.erlang.cookie` file?  Does this happen when the `clouseau.cookie` variable is not set?

2023-02-08 16:00 UTC, pgj commented
Hrm, [this does not seem to be the case](https://github.com/cloudant-labs/clouseau/blob/7a601e96c549a73abce72c640bee8cd921167bcf/src/main/scala/com/cloudant/clouseau/Main.scala#L45).  Do you think I should the change Scala code to get the default value for the `cookie` from `~/.erlang.cookie`?

2023-02-08 16:01 UTC, rnewson commented
I'm thinking of https://github.com/cloudant/scalang/blob/894bd33fc563b54c455fd78ae6ca72a2d2d25811/src/main/scala/scalang/Node.scala#L68

2023-02-08 16:35 UTC, pgj commented
> I'm thinking of https://github.com/cloudant/scalang/blob/894bd33fc563b54c455fd78ae6ca72a2d2d25811/src/main/scala/scalang/Node.scala#L68

Looks like the referenced functionality only kicks in when the `cookie` parameter is not passed along with the `NodeConfig` but that latter is Clouseau-specific and cannot be omitted.

2023-02-10 15:01 UTC, pgj commented
@rnewson do you have any comments or requests on the proposed changes?  How do you like them?

2023-02-10 15:21 UTC, rnewson requested changes
I don't think we should re-implement the code already presents in scalang. I'd modify Node.scala in scalang to add the missing `def apply(name : String, nodeConfig : NodeConfig)` and have it use `findOrGenerateCookie`, then construct the `Node` in clouseau's `Main` with those arguments if `clouseau.cookie` is not set.

2023-02-10 15:21 UTC, rnewson commented on src/main/scala/com/cloudant/clouseau/Main.scala
> +  logger.info("Erlang cookie in use: " + cookie)
the cookie value is a shared secret, it's not appropriate to print it to screen/log files.

2023-02-10 18:07 UTC, pgj commented
When I was looking at the `scalang` repository I had the impression that it is not actively maintained (the latest commit is from 9 years ago) that is why I decided not to hack on it in the first place.  But in general, I think you are right @rnewson -- I can give them a try because your way is closer to the true path.

2023-02-10 22:22 UTC, pgj commented
Opened https://github.com/boundary/scalang/pull/37 to address the `scalang` part.

2023-02-11 05:10 UTC, jaydoane commented
> When I was looking at the `scalang` repository I had the impression that it is not actively maintained (the latest commit is from 9 years ago)

We're using [this fork of scalang](https://github.com/cloudant/scalang/) which has recent activity.

2023-02-11 06:13 UTC, pgj commented
Thanks @jaydoane for the excellent hint -- I should have thought about it.  Per this suggestion, moved the pull request to https://github.com/cloudant/scalang/pull/3 .

2023-02-13 12:31 UTC, pgj commented
@rnewson rebased the solution to `scalang 1.0.1`.  Hopefully this version is now closer to the one you suggested.

2023-02-13 12:55 UTC, rnewson approved these changes
nice.

2023-02-13 13:42 UTC, merged